title: Noah Eckman
author: neckman
description: >
  Noah Eckman's homepage on the internet.

remote_theme: jekyll/minima@593a05a

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: dark # or auto if you want it to switch with your system settings.
  social_links:
    - title: Noah on Twitter
      icon: x-twitter
      url: "https://x.com/neckman"

header_pages:
  - bio.md
  - papers.md
  - blog.md
  - nature.md

#include:
#  - _includes/head-custom.html
