title: Noah Eckman
author: neckman
description: >
  Noah Eckman's homepage on the internet.

theme: minima

minima:
  skin: dark
  social_links:
    - title: Noah on Twitter
      icon: x-twitter
      url: "https://x.com/jekyllrb"

header_pages:
  - bio.md
  - papers.md
  - blog.md
  - nature.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#include:
#  - _includes/head-custom.html
