title: Noah Eckman
description: My website.
author: neckman
theme: minima

# Optional extras:
# Enable navigation links:
header_pages:
  - bio.md
  - papers.md
  - blog.md
  - nature.md
  
minima:
  skin: dark
  social_links:
    - title: Tweets from both sides of my brain
      icon: x-twitter
      url: "https://x.com/noaheckman"
    - title: LinkedIn
      icon: LinkedIn
      url: "https://www.linkedin.com/in/neckman"
      
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _includes/head-custom.html
