title: Noah Eckman
author: neckman
description: >
  Noah Eckman's homepage on the internet.

theme: minima

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: solarized-dark
  social_links:
    - title: That Website (thoughts from both sides of my brain)
      icon: x-twitter
      url: "https://x.com/noaheckman"

header_pages:
  - bio.md
  - papers.md
  - blog.md
  - nature.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#include:
#  - _includes/head-custom.html
